version: "3"

services:

  mongo:
    image: andresvidal/rpi3-mongodb3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: admin
      RESTART: unless-stopped
    volumes:
      - "/data/db:/data/db"
      - "/data/configdb:/data/configdb"
    ports:
      - "27017:27017"
      - "28017:28017"
    command: mongod --auth
